### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by James-S-Santangelo** [James-S-Santangelo/SIC#1]
- [x] Add metadata for clean datasets
- [x] Analyze data using dataset on individual plants
    - [x] Linear models with traits as response, distance to core, HCN, and their interaction as predictors.
        - [x] How should we incorporate distance to common garden into these models?
        - [x] Consider removing residual effect of dist_to_cg? If it seems that dist_to_cg matters. (KT)
    - [x] Reproductive biomass/vegetative biomass ratio as response, distance to core and distance to common garden as predictors
    - [x] Change in pollination efficiency (i.e. seed/flower ratio) among common garden plants with distance to core, HCN, and their interaction.
- [x] Change in pollination efficiency (i.e. seed/flower ratio) among field-collected inflorescences with distance to core. 
- [x] Changes in pollination with urbanization
    - [x] Changes in pollinator visitation with distance to core
    - [x] Linear regression on pollinator richness generated by rarefaction (see Larson *et al.* paper).
- [x] Multivariate trait change with urbanization. 
- [x] Check residual plots and assumptions of all modes. Are trait transformations necessary?
    - **Note:** Some residual plots from the univariate trait change models were skewed and the residuals vs. fitted showed clear fanning. I have not dealt with this yet.
- [x] Figures:
    - [x] Univariate trait change with urbanization using individual plant data
        - **Note:** I created figures using all of the data, since these are how the models were run. However, I additionally created figures using population means since the trends are more apparent.
    - [x] Pollinator observation and rarefaction analysis of pollinator richness
    - [x] Multivariate trait change
- [x] Trait correlations
    - **Note:** Most traits don't show strong correlations and those that do are not surprising (e.g. reproductive biomass and number of inflorescences). For traits that are highly correlated and show the same pattern of trait change (e.g. banner width and height), should we combine these into a single trait (e.g. flower size)?

**Comment by Ken-A-Thompson** [comment]
Some of the diagnostics reveal a few potential mistakes. For example plant 6-6-3 has negative reprod.biomass. Just have to make sure it's cleaned. Ideally we will figure this out in advance so mistakes can be worked out and samples re-weighed (and re-dried) before we start writing. @James-S-Santangelo do we still have the plant samples?

**Comment by James-S-Santangelo** [comment]
@Ken-A-Thompson Yes of course! I caught that error in one of my old script but haven't fixed it yet. I still have all of the plants and recently organized them so any mistakes like these should be super easy to fix.

**Comment by James-S-Santangelo** [comment]
Note re: Seeds/flower in field data — Report transformed and untransformed analysis and include diagnostic plots in supplement
